name: "Label Check Action"
description: "An action that will add a check to your CI that fails if the PR is lacking the provided label. We use it as a way to indicate manual QA on a PR, but you could use it for anything really."
branding:
  color: green
  icon: check
inputs:
  label-name-to-watch-for:
    description: "The label to watch for. If this label has not been applied to the PR, this check will fail. If it has, it will pass."
    required: true
runs:
  using: "node12"
  main: "index.js"
